FROM maven as build
WORKDIR /opt/networkhealth
COPY ./networkhealth .
RUN mvn package -DskipTests

FROM java:openjdk-8-jre
COPY --from=build /opt/networkhealth/target/networkhealth-0.0.1-SNAPSHOT.jar .
EXPOSE 8080
CMD java -jar networkhealth-0.0.1-SNAPSHOT.jar
